# EpiFilter Rt analysis for city- and district-level chikungunya incidence.
#
# Method: Parag KV (2021), Improved estimation of time-varying reproduction
# numbers at low case incidence and between epidemic waves. PLoS Comput Biol.
# This script implements the EpiFilter recursion on a discrete Rt grid and the
# corresponding backward smoother. It intentionally uses only base R.
#
# Run from this folder:
#   "C:/Program Files/R/R-4.4.1/bin/Rscript.exe" run_epifilter_rt.R

options(stringsAsFactors = FALSE)

# ---- Analysis settings ----------------------------------------------------
city_file <- "df_city.csv"
district_file <- "District_Cases_Level.csv"
output_dir <- "output_epifilter_SImean13.3_SIsd5.4_alpha0.5_Rmax20_eta0.20"
start_date_arg <- sub("^--start-date=", "", commandArgs(trailingOnly = TRUE)[grepl("^--start-date=", commandArgs(trailingOnly = TRUE))])
analysis_start_date <- if (length(start_date_arg) == 0L) as.Date(NA) else as.Date(start_date_arg[1L])
if (length(start_date_arg) > 1L || (!is.na(analysis_start_date) && is.na(as.numeric(analysis_start_date)))) stop("Use --start-date=YYYY-MM-DD.", call. = FALSE)
if (!is.na(analysis_start_date)) output_dir <- paste0(output_dir, "_start_", format(analysis_start_date, "%Y%m%d"))

# Serial interval (days), retained from the previous Rt script.  These should
# be varied in a sensitivity analysis because they were inferred from only nine
# high-confidence transmission pairs.
si_mean_days <- 13.30
si_sd_days <- 5.40
max_si_days <- 50L

# Local cases are the observations generated by local transmission. Imported
# cases are allowed to seed onward transmission, but only this proportion is
# counted in total infectiousness. Set to 0, 0.5, and 1 in sensitivity analyses.
imported_infectivity_weight <- 0.50

# EpiFilter grid/state model settings. The grid size is increased with Rmax so
# that grid spacing remains about 0.05 Rt units, as in the prior Rmax = 10 run.
Rmin <- 0.01
Rmax <- 20.00
m <- 400L
eta <- 0.20
credibility <- 0.95

# Missing dates are interpreted as zero reported cases. EpiFilter requires an
# equally spaced daily incidence series; set FALSE only if every date is present.
fill_missing_dates_with_zero <- TRUE

# ---- Utility functions ----------------------------------------------------
script_path <- sub("^--file=", "", commandArgs(trailingOnly = FALSE)[grepl("^--file=", commandArgs(trailingOnly = FALSE))])
base_dir <- if (length(script_path) == 1L) dirname(normalizePath(script_path)) else getwd()
resolve_path <- function(path) file.path(base_dir, path)

stop_if <- function(condition, message) {
  if (isTRUE(condition)) stop(message, call. = FALSE)
}

weighted_quantile_grid <- function(grid, probabilities, probs = c(0.025, 0.5, 0.975)) {
  stop_if(length(grid) != length(probabilities), "Grid and posterior have different lengths.")
  probabilities <- pmax(probabilities, 0)
  probabilities <- probabilities / sum(probabilities)
  cumulative <- cumsum(probabilities)
  vapply(probs, function(p) grid[which(cumulative >= p)[1L]], numeric(1))
}

discretise_serial_interval <- function(mean_days, sd_days, max_days) {
  stop_if(mean_days <= 0 || sd_days <= 0 || max_days < 1, "Serial-interval parameters must be positive.")
  shape <- (mean_days / sd_days)^2
  scale <- sd_days^2 / mean_days
  lag <- seq_len(max_days)
  # w[s] = P(s - 1 < serial interval <= s), so w[1] is the 0--1 day mass.
  w <- pgamma(lag, shape = shape, scale = scale) - pgamma(lag - 1, shape = shape, scale = scale)
  w / sum(w)
}

complete_daily_series <- function(data, group_name = NULL) {
  required <- c("date", "local", "imported")
  stop_if(!all(required %in% names(data)), paste("Input is missing:", paste(setdiff(required, names(data)), collapse = ", ")))
  data$date <- as.Date(data$date)
  stop_if(anyNA(data$date), "At least one date could not be read as YYYY-MM-DD.")
  data$local <- as.numeric(data$local)
  data$imported <- as.numeric(data$imported)
  stop_if(anyNA(data$local) || anyNA(data$imported), "Case counts must be numeric and non-missing.")
  stop_if(any(data$local < 0) || any(data$imported < 0), "Case counts cannot be negative.")

  aggregate_formula <- if (is.null(group_name)) cbind(local, imported) ~ date else as.formula(paste("cbind(local, imported) ~", group_name, "+ date"))
  collapsed <- aggregate(aggregate_formula, data = data, FUN = sum)
  if (!fill_missing_dates_with_zero) return(collapsed)

  all_dates <- seq(min(collapsed$date), max(collapsed$date), by = "day")
  if (is.null(group_name)) {
    out <- merge(data.frame(date = all_dates), collapsed, by = "date", all.x = TRUE, sort = TRUE)
  } else {
    groups <- sort(unique(collapsed[[group_name]]))
    calendar <- expand.grid(group = groups, date = all_dates, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    names(calendar)[1L] <- group_name
    out <- merge(calendar, collapsed, by = c(group_name, "date"), all.x = TRUE, sort = TRUE)
  }
  out$local[is.na(out$local)] <- 0
  out$imported[is.na(out$imported)] <- 0
  out
}

calculate_infectiousness <- function(source_incidence, serial_interval) {
  n <- length(source_incidence)
  Lambda <- numeric(n)
  for (t in seq_len(n)) {
    max_lag <- min(t - 1L, length(serial_interval))
    if (max_lag > 0L) {
      Lambda[t] <- sum(source_incidence[t - seq_len(max_lag)] * serial_interval[seq_len(max_lag)])
    }
  }
  Lambda
}

# Forward recursion: p(R_t | I_1:t). The transition is
# R_t | R_{t-1}=r ~ Normal(r, eta*sqrt(r)), evaluated on the Rt grid.
epiFilter <- function(Iday, Lday, Rgrid, eta, pR0) {
  nday <- length(Iday)
  m <- length(Rgrid)
  stop_if(length(Lday) != nday, "Iday and Lday must have the same length.")
  stop_if(length(pR0) != m, "pR0 must have one value for each Rt grid point.")

  # Rows are current states and columns are next states. Row normalization
  # preserves probability mass on the finite grid.
  pstate <- vapply(Rgrid, function(r_previous) {
    dnorm(Rgrid, mean = r_previous, sd = sqrt(r_previous) * eta)
  }, numeric(m))
  pstate <- t(pstate)
  pstate <- pstate / rowSums(pstate)

  pR <- matrix(NA_real_, nrow = nday, ncol = m)
  pRup <- matrix(NA_real_, nrow = nday, ncol = m)
  pR[1L, ] <- pR0 / sum(pR0)
  pRup[1L, ] <- pR[1L, ]

  if (nday >= 2L) {
    for (t in 2:nday) {
      prior <- drop(pR[t - 1L, ] %*% pstate)
      log_likelihood <- dpois(Iday[t], lambda = pmax(Lday[t] * Rgrid, .Machine$double.xmin), log = TRUE)
      # Scaling on the log scale avoids all-zero likelihood vectors at high incidence.
      likelihood <- exp(log_likelihood - max(log_likelihood))
      posterior_unnormalised <- prior * likelihood
      if (!is.finite(sum(posterior_unnormalised)) || sum(posterior_unnormalised) == 0) {
        posterior_unnormalised <- prior
      }
      pR[t, ] <- posterior_unnormalised / sum(posterior_unnormalised)
      pRup[t, ] <- prior
    }
  }
  list(pR = pR, pRup = pRup, pstate = pstate)
}

# Backward recursion: q(R_t | I_1:T). This is retrospective and must not be
# interpreted as a real-time estimate at date t.
epiSmoother <- function(pR, pRup, pstate) {
  nday <- nrow(pR)
  m <- ncol(pR)
  qR <- matrix(NA_real_, nrow = nday, ncol = m)
  qR[nday, ] <- pR[nday, ]
  if (nday >= 2L) {
    for (t in (nday - 1L):1L) {
      backward_factor <- qR[t + 1L, ] / pmax(pRup[t + 1L, ], .Machine$double.xmin)
      qR[t, ] <- pR[t, ] * drop(pstate %*% backward_factor)
      qR[t, ] <- qR[t, ] / sum(qR[t, ])
    }
  }
  qR
}

summarise_posterior <- function(dates, local, imported, infectiousness, posterior, Rgrid, estimate_type, area) {
  q <- t(vapply(seq_len(nrow(posterior)), function(i) {
    weighted_quantile_grid(
      grid = Rgrid,
      probabilities = posterior[i, ],
      probs = c((1 - credibility) / 2, 0.5, 1 - (1 - credibility) / 2)
    )
  }, numeric(3)))
  data.frame(
    date = dates,
    area = area,
    estimate_type = estimate_type,
    local_cases = local,
    imported_cases = imported,
    total_infectiousness = infectiousness,
    rt_mean = drop(posterior %*% Rgrid),
    rt_median = q[, 2L],
    rt_lower = q[, 1L],
    rt_upper = q[, 3L],
    pr_rt_gt_1 = rowSums(posterior[, Rgrid > 1, drop = FALSE]),
    stringsAsFactors = FALSE
  )
}

estimate_epifilter_rt <- function(series, area) {
  source_incidence <- series$local + imported_infectivity_weight * series$imported
  infectiousness <- calculate_infectiousness(source_incidence, serial_interval)
  fit <- epiFilter(Iday = series$local, Lday = infectiousness, Rgrid = Rgrid, eta = eta, pR0 = pR0)
  smooth <- epiSmoother(fit$pR, fit$pRup, fit$pstate)
  rbind(
    summarise_posterior(series$date, series$local, series$imported, infectiousness, fit$pR, Rgrid, "filtered_realtime", area),
    summarise_posterior(series$date, series$local, series$imported, infectiousness, smooth, Rgrid, "smoothed_retrospective", area)
  )
}

plot_rt <- function(result, filename, title) {
  realtime <- result[result$estimate_type == "filtered_realtime", ]
  retrospective <- result[result$estimate_type == "smoothed_retrospective", ]
  grDevices::pdf(filename, width = 10, height = 5)
  on.exit(grDevices::dev.off(), add = TRUE)
  y_upper <- max(c(realtime$rt_upper, retrospective$rt_upper, 1), na.rm = TRUE)
  plot(realtime$date, realtime$rt_median, type = "n", xaxt = "n", ylim = c(0, y_upper * 1.05), xlab = "Date", ylab = expression(R[t]), main = title)
  tick_dates <- seq(min(realtime$date), max(realtime$date), length.out = min(6L, length(realtime$date)))
  axis.Date(1, at = tick_dates, format = "%Y-%m-%d")
  polygon(c(realtime$date, rev(realtime$date)), c(realtime$rt_lower, rev(realtime$rt_upper)), col = grDevices::adjustcolor("#1b9e77", alpha.f = 0.20), border = NA)
  lines(realtime$date, realtime$rt_median, col = "#1b9e77", lwd = 2)
  lines(retrospective$date, retrospective$rt_median, col = "#d95f02", lwd = 2, lty = 2)
  abline(h = 1, lty = 3, col = "grey35")
  legend("topright", legend = c("Filtered (real-time)", "Smoothed (retrospective)"), col = c("#1b9e77", "#d95f02"), lty = c(1, 2), lwd = 2, bty = "n")
}

# ---- Run analysis ---------------------------------------------------------
dir.create(resolve_path(output_dir), showWarnings = FALSE, recursive = TRUE)

city_raw <- read.csv(resolve_path(city_file), check.names = FALSE, fileEncoding = "UTF-8-BOM")
district_raw <- read.csv(resolve_path(district_file), check.names = FALSE, fileEncoding = "UTF-8-BOM")
stop_if(!"district" %in% names(district_raw), "District input must contain a 'district' column.")
if (!is.na(analysis_start_date)) {
  city_raw$date <- as.Date(city_raw$date)
  district_raw$date <- as.Date(district_raw$date)
  city_raw <- city_raw[city_raw$date >= analysis_start_date, , drop = FALSE]
  district_raw <- district_raw[district_raw$date >= analysis_start_date, , drop = FALSE]
  stop_if(nrow(city_raw) == 0L || nrow(district_raw) == 0L, "No case records remain after start-date restriction.")
}

city_daily <- complete_daily_series(city_raw)
district_daily <- complete_daily_series(district_raw, group_name = "district")
serial_interval <- discretise_serial_interval(si_mean_days, si_sd_days, max_si_days)
Rgrid <- seq(Rmin, Rmax, length.out = m)
pR0 <- rep(1 / m, m)

city_result <- estimate_epifilter_rt(city_daily, area = "City")
district_list <- lapply(sort(unique(district_daily$district)), function(district) {
  estimate_epifilter_rt(district_daily[district_daily$district == district, c("date", "local", "imported")], area = district)
})
district_result <- do.call(rbind, district_list)

write.csv(city_daily, resolve_path(file.path(output_dir, "city_daily_incidence_completed.csv")), row.names = FALSE, fileEncoding = "UTF-8")
write.csv(district_daily, resolve_path(file.path(output_dir, "district_daily_incidence_completed.csv")), row.names = FALSE, fileEncoding = "UTF-8")
write.csv(city_result, resolve_path(file.path(output_dir, "rt_city_epifilter.csv")), row.names = FALSE, fileEncoding = "UTF-8")
write.csv(district_result, resolve_path(file.path(output_dir, "rt_district_epifilter.csv")), row.names = FALSE, fileEncoding = "UTF-8")
plot_rt(city_result, resolve_path(file.path(output_dir, "rt_city_epifilter.pdf")), "City-level EpiFilter Rt")

metadata <- c(
  "Method: EpiFilter discrete-grid filter and backward smoother (Parag 2021).",
  paste("Input city file:", city_file),
  paste("Input district file:", district_file),
  paste("Date range:", min(city_daily$date), "to", max(city_daily$date)),
  paste("Analysis start-date restriction:", ifelse(is.na(analysis_start_date), "none", as.character(analysis_start_date))),
  paste("Daily dates added at city level:", nrow(city_daily) - nrow(city_raw)),
  paste("Serial interval mean (days):", si_mean_days),
  paste("Serial interval SD (days):", si_sd_days),
  paste("Serial interval upper truncation (days):", max_si_days),
  paste("Imported-case infectivity weight:", imported_infectivity_weight),
  paste("Rt grid:", Rmin, "to", Rmax, "with", m, "points"),
  paste("State-noise eta:", eta),
  "filtered_realtime uses data through each date only; smoothed_retrospective uses the full time series."
)
writeLines(metadata, resolve_path(file.path(output_dir, "run_metadata.txt")), useBytes = TRUE)

message("EpiFilter analysis completed.")
message("Outputs: ", normalizePath(resolve_path(output_dir)))
